name: Version Bump

on: [delete]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Trigger Version Bump workflow
        run: gh workflow run update-cmo-deps-versions.yaml -f name=hello

